### ISSUE TITLE
Sprockets::Rails::Helper::AssetNotFound in Site#index

### ISSUE THREAD

**Issue by mh-github** [jameshibbard/react-rails-crud-app#54]
I cloned the repository and ran the commands exactly as given in README.md. Got an error when I accessed localhost:3000 --
![image](https://user-images.githubusercontent.com/2176303/171791088-c366f6de-2d4a-4c9d-a4f2-ad4f4f2f8cc5.png)

**Comment by mh-github** [comment]
Okay, my bad.
I ran rails s instead of bin/dev.
I did gem install foreman and bin/dev.
The application runs.

**Comment by jameshibbard** [comment]
Hi,
>  I did gem install foreman and bin/dev.

If you are going the esbuild route, you shouldn't need to install foreman. It should be enough to run `rails s` in one terminal window, and `bin/dev` in a second.

Either way, glad you got it working.
